Lag mitigation for APS (heavy only)
Gamer-Dad/warlordsredux.altis pull request #163
Opened 2023-07-27 22:32 UTC by rookiv

This is a more foolproof method of addressing bypassing of APS under heavy lag conditions.

2023-07-27 22:39 UTC, MrThomasM commented
I will have a look at this tmrw morning and check the rest.

2023-07-27 22:39 UTC, MrThomasM commented
of the code*

2023-07-28 08:13 UTC, MrThomasM requested changes

2023-07-28 08:13 UTC, MrThomasM commented on scripts/DAPS/Scripts/APS/fn_LagMitigation.sqf
> +if (_unit distance _source < 40) exitWith {	// too close?
change this to 30 meters so it matches the other ranges

2023-07-28 17:45 UTC, rookiv commented on scripts/DAPS/Scripts/APS/fn_LagMitigation.sqf
> +if (_unit distance _source < 40) exitWith {	// too close?
Done.

2023-07-29 21:49 UTC, merged